css:
  channel: '#frontend-pull-reqs'
  language: 'css'

go:
  channel: '#go-pull-requests'
  language: 'go'

javascript:
  channel: '#js-pull-requests'
  language: 'javascript'

python:
  channel: '#python-pull-requests'
  language: 'python'

ruby:
  channel: '#ruby-pull-requests'
  language: 'ruby'

shell:
  channel: '#shell-pull-requests'
  language: 'shell'
