18f:
  channel: "#open-pull-requests"

  exclude_titles:
    - '[DO NOT MERGE]'
    - 'DO NOT MERGE'
    - "DON'T MERGE"
    - 'DONT MERGE'
    - 'WORK IN PROGRESS'
    - 'WIP'

  exclude_labels:
    - 'wip'

  ignored_repos:
    - 'C2'
    - 'college-choice'
    - 'openFEC'
    - 'openFEC-web-app'
