# Please insert new items alphabetically.

core-formats:
  members:
    - benilovj
    - benlovell
    - binaryberry
    - boffbowsh
    - fofr
    - jamiecobbett
    - tommyp
    - gpeng
    - dsingleton

  channel:
    "#core-formats"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

custom:
  members:
    - brenetic
    - sihugh
    - issyl0
    - jennyd
    - marksheldonGDS
    - tommyp
    - h-lame
    - davidbasalla

  channel:
    "#custom"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

finding-things:
  members:
    - alextea
    - bishboria
    - jackscotti
    - mobaig
    - rboulton
    - stephen-richards
    - tijmenb

  channel:
    "#finding-things"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

testing:
  members:
    - ajlanghorn
    - benilovj
    - binaryberry
    - boffbowsh
    - fofr
    - jamiecobbett

  channel:
    "#testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP
