envato-market:
  members: []
  repos:
    - docs
    - envato.com
    - marketplace
    - marketplace-puppet
    - new-coding-test
    - our-boxen
    - webuild.envato.com

  channel: '#marketplacedev'

