exclude_titles:
  - '[DO NOT MERGE]'
  - 'DO NOT MERGE'
  - "DON'T MERGE"
  - 'DONT MERGE'
  - "[DON'T MERGE]"
  - 'WORK IN PROGRESS'
  - 'WIP'
  - '[WIP]'

exclude_labels:
  - 'wip'

ignored_repos:
  - 'C2'
  - 'college-choice'
  - 'data-private'
  - 'identity-dashboard'
  - 'identity-devops'
  - 'identity-idp'
  - 'identity-private'
  - 'identity-sp-rails'
  - 'openFEC'
  - 'openFEC-web-app'
